### ISSUE TITLE
(suggest) you should add custom style for remove arrow

### ISSUE THREAD

**Issue by yudhis8** [hungdev/react-native-customize-selected-date#1]
hey, i think you should have this props to custom style arrow just like visible and custom icon for arrow :)

**Comment by hungdev** [comment]
@yudhis8  thank for your issue. in the next version, I will add custom props style and others props to export.
currently, I'm so busy. So when i have free time, i will do that.
And pull request are welcome.

**Comment by hungdev** [comment]
I've updated.
